---
title: "redes_sociales"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{redes_sociales}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}


library(magrittr)
library(dplyr)
library(lubridate)
library(highcharter)
library(quanteda)
library(rtweet)
library(ggplot2)
library(quanteda.textplots)
library(here)

```


```{r}
proyectos <- tibble( grupo = sample(c("Tweet", "Menciones", "RT", "Likes"),
                                    prob = c(.2,.2 ,.3, .3), size = 100, replace = T),
                     fecha = sample(seq(today()-100, today(), length.out = 11), size = 100, replace = T )) %>%
  arrange(fecha) %>% 
  group_by(fecha, grupo) %>%
  summarise(n=n()) 

tempo <- entrenamiento %>%
         mutate(fecha=floor_date(TW_CreatedAt, "day"), 
                fecha=as.Date(fecha), 
                tuits=1) %>%
         select(TW_Entities:TW_InReplyToStatusID, tuits, TW_FavoriteCount:fecha) %>% 
         group_by(fecha) %>%
         summarise(across(tuits:TW_RetweetCount,
                          ~ sum(.x, na.rm = TRUE))) %>% 
         rename("Tweets"="tuits", "Favoritos"="TW_FavoriteCount", 
                "RTs"="TW_RetweetCount") %>% 
         tidyr::gather(grupo, n, "Tweets":"RTs") 

seguidores <- entrenamiento %>% 
              mutate(fecha=floor_date(fechaInicio, "day"), 
                     fecha=as.Date(fecha)) %>% 
              select(fecha, TW_Entities, TW_FollowersCount) %>% 
              unique() %>% 
              filter(TW_FollowersCount==max(TW_FollowersCount))



```

```{r}


reach <- function(bd){
  hchart(bd, hcaes(x = fecha, y = TW_FollowersCount, group = TW_Entities), type = "line") %>%
    hc_plotOptions(line= list(lineWidth = 4,
                              marker = list(radius =0),
                              stickyTracking=F)) %>%
    hc_xAxis(crosshair = T, title = list(text = "Fecha",  style = list(color = "#FFF")), type = "datetime",
             lineWidth = 0, tickWidth  = 0, gridLineWidth =0,
             showLastLabel= F,
             labels = list(format = '{value:%b %d}', step = 1, 
                           style = list(fontSize = "18px",
                                        color = "#13384D"))) %>%
    hc_yAxis(crosshair = F, title = list(text = "Total de proyectos", style = list(color = "#FFF")), 
             dashStyle = "dot",
             gridLineWidth =.5, showFirstLabel = F, gridLineColor = "",
             labels = list( style = list(fontSize = "12px") )) %>%
    #title
    hc_title(text = "<b>Proyectos de ley</b>",  style = list(color = "#FFF")) %>%
    #tooltip
    hc_tooltip(
      borderWidth= 0,
      outside = T,
      textOutline= "3px contrast",
      shadow=F,
      shared = T,
      split = F,
      headerFormat= '<span style="font-size: 10px">{point.key}</span><br/>'
      # pointFormat = '<span style="color:{point.color}">●</span> <b> {point.candidato}<b><br> p. clave: {point.palabra}<br> {point.n} tuits <br> {point.rt} retuits<br> {point.favs} favoritos<br>'
    ) %>%
 hc_add_theme(hc_theme_gridlight()) %>% 
    hc_colors(colors = c("#2C6170", "#FF6B6B", "#FFE66D", "steelblue")) %>%
    hc_chart(style = list(fontFamily = "Avenir next"
    ))
  
}


hchart(tempo, hcaes(x = fecha, y = n, group = grupo), type = "line") %>%
    hc_plotOptions(line= list(lineWidth = 4,
                              marker = list(radius =6),
                              stickyTracking=F)) %>%
    hc_xAxis(crosshair = T, title = list(text = F), type = "datetime",
             lineWidth = 0, tickWidth  = 0, gridLineWidth =0,
             showLastLabel= T,
             labels = list(format = '{value:%b %d}', step = 1, 
                           style = list(fontSize = "18px",
                                        color = "#13384D"))) %>%
  hc_yAxis(labels= list(formatter = JS("function(){ return Math.abs(this.value); }"))) %>%
    #title

      hc_colors(colors = c("#2C6170", "#FF6B6B", "#FFE66D")) %>%
    #tooltip
    # hc_tooltip(
    #   borderWidth= 0,
    #   outside = T,
    #   textOutline= "3px contrast",
    #   shadow=F,
    #   shared = T,
    #   split = F,
    #   headerFormat= '<span style="font-size: 10px">{point.key}</span><br/>'
    # ) %>%

    hc_chart(style = list(fontFamily = "Avenir next"
    ))%>%
    hc_add_theme(hc_theme_google())%>%
    #title
    hc_title(text = "Alcance en redes sociales",  style = list(fontWeight = "bold", fontSize = "15px"))


reach(tempo)

```

```{r}


bd <- tibble(votos = sample(30:78, size = 172, replace = T),
             voto = sample(c("Negativo", "Positivo"), size = 172, replace = T, prob = c(.5, .5))) %>%
  mutate(mes = cut(votos,c(17,29,39,49,59,69,79, 89,100),
                   labels = c("Semana 1", "Semana 2", "Semana 3", "Semana 4", "Semana 5", "Semana 6", "Semana 7", "Semana 8"))) %>%
  count(mes, voto) %>%
  mutate(n = as.double(n),
         n2= case_when(voto == "Negativo"~ n*-1,
                       voto == "Positivo"~ n))

graficando_saldo <- function(bd){
  hchart(bd, hcaes(y = n2, group = voto, x = mes), type = "bar") %>%
    hc_colors(colors = c("#f03b20", "#31a354")) %>%
    hc_plotOptions(bar = list(stacking = T, borderRadius = 5,
                              dataLabels= list(enabled =F,
                                               align= "center",
                                               inside= F,
                                               # rotation = 5,
                                               verticalAlign= 'top',
                                               # x = -5,
                                               crop= F,
                                               overflow= "none",
                                               style=list(color="BLACK", fontSize = "25px", textOutline= "3px contrast"),
                                               format = paste0("{point.n:,.0f} ")
                                               
                              )
    ))%>%
    
    hc_yAxis(labels= list(formatter = JS("function(){ return Math.abs(this.value); }")))
  
}

graficando_saldo(bd)

```

```{r}
en <- entrenamiento %>% 
      filter(!is.na(calificacion)) %>% 
      select(calificacion, TW_Text) 
procesando_nube <- function(DB){

corp_quanteda <- corpus(DB, text_field = "TW_Text")
Nube <- dfm(corp_quanteda, remove = stopwords("spanish"), 
            remove_punct = TRUE, groups = "calificacion")


}

graficando_nube <- function(DB){
  nube <- textplot_wordcloud(Nube, comparison = TRUE, max_words =300,
                             min_count  = 5, adjust = 0, 
                   rotation   = 0.1, random_order = FALSE,random_color = FALSE,
                   ordered_color = FALSE,
                   color = c("#cb2833", "#0f4c42", "grey")) + theme_minimal()
  return(nube)
}

Nube <- procesando_nube(en)
graficando_nube(Nube)


```

```{r}
procesando_nube <- function(DB){
DB$sentido = sample(c("Negativo", "Positivo"), 
                       size = 3199, replace = T, prob = c(.5, .5))
corp_quanteda <- corpus(DB)
Nube <- dfm(corp_quanteda, remove = stopwords("spanish"), 
            remove_punct = TRUE, groups = "sentido")


}

Nube <- procesando_nube(words)

procesando_red_menciones <- function(DB){
tag_dfm <- dfm_select(DB, pattern = ("@*"))
toptag <- names(topfeatures(tag_dfm, 20))
tag_fcm <- fcm(tag_dfm)
topgat_fcm <- fcm_select(tag_fcm, pattern = toptag)
}

red <- procesando_red_menciones(Nube)

graficando_red <- function(DB){
textplot_network(DB,
                 min_freq = 0.1, edge_alpha = 0.8, 
                 edge_size = 5)

}

graficando_red(red)


```

```{r}


Nube <- procesando_nube(words)

procesando_red_hashtag <- function(DB){
tag_dfm <- dfm_select(DB, pattern = ("#*"))
toptag <- names(topfeatures(tag_dfm, 20))
tag_fcm <- fcm(tag_dfm)
topgat_fcm <- fcm_select(tag_fcm, pattern = toptag)
}

red <- procesando_red_hashtag(Nube)

graficando_red <- function(DB){
textplot_network(DB,
                 min_freq = 0.1, edge_alpha = 0.8, 
                 edge_size = 5)

}

graficando_red(red)




```
```{r}

en <- entrenamiento %>% 
  collect() %>% 
  mutate(fecha=floor_date(TW_CreatedAt,unit="day"), 
         fecha=as.Date(fecha)) %>% 
   count(fecha, calificacion) %>% 
        filter(!is.na(calificacion)) %>% 
   mutate(color=if_else(calificacion=="Negativo", "#f03b20", 
                if_else(calificacion=="Positivo", "#31a354", "#F0F0F0"))) 
  # mutate(fecha=datetime_to_timestamp(fecha))




# secu <- tibble(fecha=seq(min(en$fecha), today(), by = "days"), 
#                calificacion=sample(c("Positivo", "Negativo", "Neutral"),  size = as.numeric(today()-min(en$fecha))+1, 
#                                    replace = T)) %>% 
#         tidyr::expand(fecha, calificacion) %>% 
#        left_join(en)
# 
# secu$n[is.na(secu$n)] <-0


hchart(en, hcaes(x = fecha,y = n, group = calificacion, color=color), type = "column", stacking = "normal") %>%
    hc_colors(colors = unique(en$color[order(en$calificacion)])) %>%
    hc_yAxis(labels= list(formatter = JS("function(){ return Math.abs(this.value); }"))) %>%
    hc_xAxis(crosshair = T, title = list(text = F), type = "datetime",
             lineWidth = 0, tickWidth  = 0, gridLineWidth =0,
             showLastLabel= T,
             labels = list(format = '{value:%b %d}', step = 1, 
                           style = list(fontSize = "18px",
                                        color = "#13384D"))) %>%
    hc_plotOptions(bar = list(stacking = T, borderRadius = 5,
                              dataLabels= list(enabled =F,
                                               align= "center",
                                               inside= F,
                                               # rotation = 5,
                                               verticalAlign= 'top',
                                               # x = -5,
                                               crop= F,
                                               overflow= "none",
                                               style=list(color="BLACK", fontSize = "25px", textOutline= "3px contrast"),
                                               format = paste0("{point.n:,.0f} ")
                                               
                              )
    ))%>%

    # hc_add_theme(hc_theme_google())%>%
    #title
    hc_title(text = "Balance de comentarios",  style = list(fontWeight = "bold", fontSize = "15px")) 
  

```

